---
author: 'JOÃO VITOR FERREIRA CAVALCANTE'
local: NATAL - RN
date_year: '2025'
date_month: 'Setembro'
date_day: '31'
institution: 'Universidade Federal do Rio Grande do Norte'
inst_short: 'UFRN'
division: 'Instituto Metrópole Digital'
coordinator: Rodrigo Juliani Siqueira Dalmolin
advisor: Rodrigo Juliani Siqueira Dalmolin
# If you have more two advisors, un-silence line 7
#altadvisor: 'Your Other Advisor'
examiner:
- title: Prof.
  name: Renan Cipriano Moioli
  degree: Dr.
  institution: Universidade Federal do Rio Grande do Norte
  inst_short: UFRN
  role: Interno do Programa
- title: Prof.
  name: Daniel Carlos Ferreira Lanza
  degree: Dr.
  institution: Universidade Federal do Rio Grande do Norte
  inst_short: UFRN
  role: Interno do Programa
- title: Prof.
  name: Marcel da Câmara Ribeiro-Dantas
  degree: Dr.
  institution: Universidade Potiguar
  inst_short: UNP
  role: Externo à Instituição
department: |
  Programa de Pós-Graduação em Bioinformática
degree: 'Mestre em Bioinformática'
level: 'mestrado'
doc_type: 'Defesa de Mestrado'
title: 'O Ecossistema Computacional da Metagenômica'
subtitle: 'Fluxos de Trabalho, Reprodutibilidade e Replicabilidade'
knit: "bookdown::render_book"
site: bookdown::bookdown_site
output: 
  ufscdown::thesis_pdf:
    citation_package: biblatex
    bib_engine: biber
  ufscdown::thesis_gitbook: default
  ufscdown::thesis_word: default
  ufscdown::thesis_epub: default
# If you are creating a PDF you'll need to write your preliminary content (e.g., 
# abstract, acknowledgements) here or use code similar to line 43-44 for the 
# .RMD files. If you are NOT producing a PDF, you can delete or silence lines 
# 42-59 in this YAML header.
abstract: |
  `r if(knitr:::is_latex_output()) paste(readLines("00-abstract.Rmd"), 
  collapse = '\n  ')`
palavras-chave: [Palavra-chave 1, Palavra-chave 2]
foreignabstract: |
  `r if(knitr:::is_latex_output()) paste(readLines("00-foreignabstract.Rmd"), 
  collapse = '\n  ')`
# If you'd rather include the preliminary content in files instead of inline
# like below, use a command like that for the abstract above.  Note that a tab 
# is needed on the line after the `|`.
keyword: [Keyword 1, Keyword 2]
epigrafe: |
  | "Eppur si muove!"  
  | (Galileu Galilei, 1633)
# Specify the location of the bibliography below
bibliography: ["bib/thesis.bib", "bib/discussion.bib", "bib/pkgs.bib"]
link-citations: yes
dedication: |
  Non ut sit repellendus ea sunt dolor.
thanks: |
  | Nihil ipsum velit cupiditate. Facilis inventore eveniet illo et.
  | Fugit unde cumque necessitatibus repudiandae non.
  | Voluptatem hic a numquam enim aperiam voluptatem. 
# If you prefer blank lines between paragraphs, un-silence lines  74-75 (this 
# requires package tikz)
header-includes:
- \usepackage{tikz}
---

```{r include_packages, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = FALSE, message=FALSE, 
                      warning = FALSE, fig.ext='png', fig.align='center', 
                      fig.path = "images/", fig.pos = "H", dev = "png", 
                      dpi = 600, out.width = "70%")
type <- knitr::opts_knit$get("rmarkdown.pandoc.to")
# This chunk ensures that the ufscdown package is
# installed and loaded. This ufscdown package includes
# the template files for the thesis.
if(!require(remotes))
  install.packages("remotes", repos = "http://cran.rstudio.com")
if(!require(ufscdown))
  remotes::install_github("lfpdroubi/ufscdown")
library(ufscdown)
```

# Introdução {#intro}

## Visão Geral - Metagenômica

A história da vida microscópica, ou microbiana, no planeta Terra supera a história da vida macroscópica por milhares de anos [@magnabosco2024]. A metagenômica surge como uma abordagem que possibilita descobertas acerca da vida microbiana através do sequenciamento genético. Avanços no que viria eventualmente a se tornar a metagenômica surgem ainda nos anos 90, com o primeiro sequenciamento de genoma completo de um organismo de vida livre, a bactéria *Haemophilus influenza* [@wooley2010]. Esse ponto na história científica marca o primeiro uso bem sucedido do que vem a ser chamado de *whole-genome shotgun*, ou sequenciamento de genoma completo, no qual a amostra possui seu conteúdo genético fragmentado em *reads*, ou leituras, que são então sequenciadas. Essa técnica viria a ser refinada e aplicada para amostras ambientais, seja este ambiente uma amostra de solo florestal ou uma biópsia intestinal. Nessa nova técnica se buscou sequenciar o conteúdo genético que compreenda os diferentes microorganismos presentes em tais amostras, originando assim o que será aqui descrito como \gls{MS}.

No entanto, o estudo de comunidades microbianas se populariza de fato com uma técnica que não busca capturar o conteúdo genético total de uma amostra, mas apenas uma subregião de seu \gls{DNA} ribossomal que possua ao mesmo tempo regiões conservadas, capaz de serem passíveis de anelamento por *primers*, e regiões hipervariáveis, capazes de distinguir um microorganismo de outro. Em bactérias o ribotipo selecionado foi o \gls{DNA} que codifica a subunidade 16S, que é amplificada e então sequenciada. O \gls{16S}, também denominado metataxonômica [@marchesi2015], possibilitou uma maneira simples, e pouco computacionalmente intensiva quando comparada à \gls{MS} [@tremblay2022], para realizar identificação de táxons bacterianos em uma amostra ambiental. Ademais, técnicas computacionais posteriores ultimamente facilitariam a conexão de informação funcional às abundâncias taxonômicas obtidas através desta técnica.

Dessa maneira, possuímos atualmente, duas possíveis abordagens para se estudar comunidades microbianas, a \gls{MS} e o \gls{16S}. Essas abordagens, por se basearem de aspectos distintos do microbioma, tipicamente são utilizadas de forma separada - e não integrativa - por estudos. Apesar disso, a integração de dados provenientes das duas abordagens pode auxiliar a remover vieses experimentais específicos de cada técnica, e, dessa maneira, conferir maior confiabilidade aos resultados [@yue2023].

## O Ecossistema computacional em Metagenômica

As metodologias de processamento de dados \gls{16S} em grande parte já estão estabelecidas, dada a idade mais avançada da abordagem. Nesse sentido, vemos que o cerne das abordagens trata de atribuir identificadores únicos às sequências 16S obtidas, caracterizando assim táxons distintos. Esses identificadores podem ser atribuídos através de métodos de agrupamento, caracterizando as abordagens baseadas em \gls{OTU}, que agrupam sequências com pelo menos 97% de identidade em grupos biológicos distintos, ou abordagens baseadas em \gls{ASV}, que, através de modelos estatísticos, tentam definir variações biológicas reais na sequência - contrastadas com variações devido a erros de sequenciamento, e dessa maneira obter uma resolução taxonômica maior comparada às baseadas em \gls{OTU} [@chiarello2022]. Nesse contexto, observamos metodologias que buscam, a partir dos \gls{OTU} ou \gls{ASV} identificados, inferir abundâncias de vias metabólicas específicas, tirando proveito de bancos de dados de informação curada a respeito desses táxons que possua mapeamento das famílias gênicas de seu genoma a funções biológicas [@douglas2020].

Por outro lado, o campo do desenvolvimento de metodologias para dados de \gls{MS} ainda é bastante fértil, com novas técnicas computacionais desenvolvidas rotineiramente [@liu2021]. De forma geral, podemos agrupar as metodologias em duas grandes categorias: Metodologias livres de montagem, isto é, aquelas que se utilizam apenas da informação contidas nas leituras para obter seus resultados, e metodologias baseadas em montagem, que primeiro realizam a montagem de leituras em sequências contíguas (ou \textit{contigs}), que fornecerá então a base para o processamento seguinte [@breitwieser2019]. Apesar da capacidade que métodos baseados em montagem tem de descobrir novos organismos e montar genomas inéditos, métodos livres de montagem apresentam certas vantagens, sobretudo quando consideramos dados com baixa cobertura de sequência, o que pode resultar em montagens pouco precisas [@ayling2020].

No que se diz respeito a essas metodologias, vemos que as baseadas em montagem são amplas e cobrem os mais diversos aspectos do processamento de dados de \gls{MS}, com exemplos como nf-core/mag [@krakau2022] e metaphor [@salazar2023]. No entanto, quando observamos métodos livres de montagem, vemos um cenário mais escasso, sobretudo quando consideramos apenas fluxos de trabalho, ou *pipelines*, orquestrados por linguagems de gerenciamento de metodologias científicas, como Nextflow [@ditommaso2017] ou Snakemake [@mölder2021], e que adiram a boas práticas de desenvolvimento de *software* científico, como isolamento de dependências, instalação fácil e documentação descritiva, com exemplos [@mangul2019]. No contexto de métodos livres de montagem para dados \gls{MS}, vale ressaltar o fluxo de trabalho MEDUSA [@morais2022], que apresentou boa sensitividade e flexibilidade para análises de classificação taxonômica e anotação funcional.

Nesse sentido, há a necessidade de desenvolver uma metodologia para dados de \gls{MS} que siga boas práticas de desenvolvimento de software e que tenha como princípios norteadores a reprodutibilidade, documentação expansiva e interpretabilidade. Este último ponto que se torna especialmente relevante ao considerarmos a complexidade e a alta dimensionalidade desses dados.

## Desenvolvimento de Software em Bioinformática

- Princípios
- Pipelines
- Conteinerização
- Reprodutibilidade e replicabilidade